# Generated by Django 2.1 on 2019-09-08 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+ (positive)'), ('A-', 'A- (negative)'), ('B+', 'B+ (positive)'), ('B-', 'B- (negative)'), ('AB+', 'AB+ (positive)'), ('AB+', 'AB- (negative)'), ('O+', 'O+ (positive)'), ('O+', 'O- (negative)')], default='O+', max_length=3)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(70)])),
            ],
        ),
    ]
