# Generated by Django 2.1 on 2019-09-08 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_donor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='phone_number',
            field=models.CharField(default='', max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be of the form: 01XXXXXXXXX', regex='^[0]{1}[\\d]{10}')]),
        ),
    ]
