# Generated by Django 2.1 on 2019-09-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_donor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
